---
- hosts: all
  gather_facts: True
  vars:
      username: '{{ rhsm_username }}'
      password: '{{ rhsm_password }}'
  tasks:
    - debug:
        var: username
        
    - debug:
        var: password
