- name: Playbook to download docker images
  hosts: all
  gather_facts: false
  vars:
    registry_address: "quay.io"
    docker_repository: "nvidia"
    nexus_docker_repo: "gcr.io"
  tasks:

    - name: way1 - 1
      debug:
        msg: "docker pull {{ nexus_docker_repo }}/nginx:1.20.1"
    - name: way1 - 2
      debug:
        msg: "docker pull {{ nexus_docker_repo }}/python:3.9"

    - name: way2 - 1 
      debug:
        msg: "docker pull {{ bcm_artifactory_docker_url }}/{{ bcm_artifactory_docker_repo }}/nginx:1.20.1"
    - name: way2 - 2
      debug:
        msg: "docker pull {{ bcm_artifactory_docker_url }}/{{ bcm_artifactory_docker_repo }}/python:3.9"
    
    - name: way3 - 1
      debug:
        msg: "docker pull {{ registry_address }}/{{ docker_repository }}/nginx:1.20.1"
    - name: way3 - 2
      debug:
        msg: "docker pull {{ registry_address }}/{{ docker_repository }}/python:3.9"
    

# docker_repository: '{{ bcm_artifactory_docker_repo }}'
# nexus_docker_repo: '{{ bcm_artifactory_url }}/{{ bcm_artifactory_docker_repo }}'
# registry_address: '{{ bcm_artifactory_url }}'
