- name: print vault creds
  hosts: localhost
  gather_facts: false
  tasks:
    - name: print
      debug:
        msg: "{{ vault_address }} - {{ vault_namespace }} - {{ vault_role_id }} - {{ vault_secret_id }}"
 
