---
- hosts: all
  gather_facts: true
  tasks:
    - debug:
        var: ansible_distribution_release
        
    - name: msg
      debug:
        msg: ansible_distribution_release
        
    - debug:
        var: ansible_distribution_major_version
        
    - name: msg
      debug:
        msg: ansible_distribution_major_version
        
    - debug:
        var: docker_versioned_pkg
        
    - name: msg
      debug:
        msg: docker_versioned_pkg
        
    - debug:
        var: docker_version
        
    - name: msg
      debug:
        msg: docker_version
        
    - debug:
        var: docker_versioned_pkg[docker_version | string]
        
    - name: msg
      debug:
        msg: docker_versioned_pkg[docker_version | string]
        
#     - name: Ensure old versions of Docker are not installed. | Debian
#       apt:
#        name: '{{ docker_remove_packages_apt }}'
#        state: absent
#   when:
#     - (docker_versioned_pkg[docker_version | string] is search('docker-ce'))
