---
- name: Checkout Local Kubesray Branch
  hosts: localhost
  gather_facts: false
  tasks:
    - block:
        - name: Install Git Client
          yum:
            name: git
            state: present

        - name: Checkout kubespray branch to {{ kubespray_branch }}
          shell: "git checkout {{ kubespray_branch }}"

        - name: Git branch status
          shell: "git branch"
      when: kubespray_branch is defined

    - debug: 
        msg: "ks-1.20"
        
